#!/bin/sh -e
# mails todo list and unfiled notes to me, unless empty

tempfile=`mktemp /tmp/mailXXXXXXXX`
todofile="$HOME/org/todo.org"

addline ()  { echo $1 >> $tempfile ; }
addfile ()  { cat  $1 >> $tempfile ; }

addline "To: John MacFarlane <jgm@berkeley.edu>"
addline "Subject: Todo list" 
addline ""
addline "Good morning John!" 
addline ""

addline "Here are some things to work on today:"
addline ""
sed -ne '/TODO/p' $todofile  >> $tempfile

cat $tempfile | /usr/sbin/sendmail -F "Your Computer" -f "jgm" -i jgm@berkeley.edu
rm $tempfile

